cmake_minimum_required(VERSION 3.10)
project(ddnet_demo C)
if(MSVC)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)
endif()
add_library(ddnet_demo INTERFACE)
target_include_directories(ddnet_demo INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})

enable_testing()
add_subdirectory(tests)

option(EXAMPLES "Build the example executables" OFF)
if(EXAMPLES)
  add_executable(example_write example_write.c ddnet_maploader/ddnet_map_loader.c)
  target_link_libraries(example_write PRIVATE z)
  if(UNIX)
    target_link_libraries(example_write PRIVATE m)
  endif()
  add_executable(example_read example_read.c ddnet_maploader/ddnet_map_loader.c)
  target_link_libraries(example_read PRIVATE z)
  if(UNIX)
    target_link_libraries(example_read PRIVATE m)
  endif()
endif()
